sudo: required

language: go

go:
- '1.10'

services: docker

before_install:
  - bundle install
  - rake install

script:
  - rake

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag $TRAVIS_REPO_SLUG $TRAVIS_REPO_SLUG:dev;
    docker push $TRAVIS_REPO_SLUG:dev;
    fi
  - if [ $TRAVIS_TAG ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

    docker tag $TRAVIS_REPO_SLUG:dev $TRAVIS_REPO_SLUG:latest;
    docker push $TRAVIS_REPO_SLUG:latest;

    docker tag $TRAVIS_REPO_SLUG $TRAVIS_REPO_SLUG:${TRAVIS_TAG:1};
    docker push $TRAVIS_REPO_SLUG:${TRAVIS_TAG:1};
    fi
