// Code generated by "stringer -type=TicketStatus"; DO NOT EDIT.

package projection

import "strconv"

const _TicketStatus_name = "TicketStatusIssuedTicketStatusPaid"

var _TicketStatus_index = [...]uint8{0, 18, 34}

func (i TicketStatus) String() string {
	if i < 0 || i >= TicketStatus(len(_TicketStatus_index)-1) {
		return "TicketStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TicketStatus_name[_TicketStatus_index[i]:_TicketStatus_index[i+1]]
}
