// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

/*
Package events is a generated protocol buffer package.

It is generated from these files:
	events.proto

It has these top-level messages:
	TicketIssued
	TicketPaid
	TicketComplete
*/
package events

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TicketIssued struct {
	At       *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=at" json:"at,omitempty"`
	TicketID string                     `protobuf:"bytes,2,opt,name=ticketID" json:"ticketID,omitempty"`
}

func (m *TicketIssued) Reset()                    { *m = TicketIssued{} }
func (m *TicketIssued) String() string            { return proto.CompactTextString(m) }
func (*TicketIssued) ProtoMessage()               {}
func (*TicketIssued) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TicketIssued) GetAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.At
	}
	return nil
}

func (m *TicketIssued) GetTicketID() string {
	if m != nil {
		return m.TicketID
	}
	return ""
}

type TicketPaid struct {
	At       *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=at" json:"at,omitempty"`
	TicketID string                     `protobuf:"bytes,2,opt,name=ticketID" json:"ticketID,omitempty"`
}

func (m *TicketPaid) Reset()                    { *m = TicketPaid{} }
func (m *TicketPaid) String() string            { return proto.CompactTextString(m) }
func (*TicketPaid) ProtoMessage()               {}
func (*TicketPaid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TicketPaid) GetAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.At
	}
	return nil
}

func (m *TicketPaid) GetTicketID() string {
	if m != nil {
		return m.TicketID
	}
	return ""
}

type TicketComplete struct {
	At       *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=at" json:"at,omitempty"`
	TicketID string                     `protobuf:"bytes,2,opt,name=ticketID" json:"ticketID,omitempty"`
}

func (m *TicketComplete) Reset()                    { *m = TicketComplete{} }
func (m *TicketComplete) String() string            { return proto.CompactTextString(m) }
func (*TicketComplete) ProtoMessage()               {}
func (*TicketComplete) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TicketComplete) GetAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.At
	}
	return nil
}

func (m *TicketComplete) GetTicketID() string {
	if m != nil {
		return m.TicketID
	}
	return ""
}

func init() {
	proto.RegisterType((*TicketIssued)(nil), "events.TicketIssued")
	proto.RegisterType((*TicketPaid)(nil), "events.TicketPaid")
	proto.RegisterType((*TicketComplete)(nil), "events.TicketComplete")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2d, 0x4b, 0xcd,
	0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0xa4, 0xe4, 0xd3, 0xf3,
	0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1, 0xa2, 0x49, 0xa5, 0x69, 0xfa, 0x25, 0x99, 0xb9, 0xa9, 0xc5,
	0x25, 0x89, 0xb9, 0x05, 0x10, 0x85, 0x4a, 0x61, 0x5c, 0x3c, 0x21, 0x99, 0xc9, 0xd9, 0xa9, 0x25,
	0x9e, 0xc5, 0xc5, 0xa5, 0xa9, 0x29, 0x42, 0x5a, 0x5c, 0x4c, 0x89, 0x25, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xdc, 0x46, 0x52, 0x7a, 0x10, 0xdd, 0x7a, 0x30, 0xdd, 0x7a, 0x21, 0x30, 0xdd, 0x41, 0x4c,
	0x89, 0x25, 0x42, 0x52, 0x5c, 0x1c, 0x25, 0x10, 0xbd, 0x2e, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x70, 0xbe, 0x52, 0x08, 0x17, 0x17, 0xc4, 0xdc, 0x80, 0xc4, 0x4c, 0xea, 0x99, 0x1a, 0xc1,
	0xc5, 0x07, 0x31, 0xd5, 0x39, 0x3f, 0xb7, 0x20, 0x27, 0xb5, 0x24, 0x95, 0x5a, 0x26, 0x27, 0xb1,
	0x81, 0xf5, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x16, 0x78, 0xc1, 0x47, 0x47, 0x01, 0x00,
	0x00,
}
